name: flutterblogapp
description: "Mobile app for the Real University Student blog."
publish_to: "none"
version: 1.4.11+2

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_settings: ^7.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.11.0
  firebase_remote_config: ^6.5.3
  font_awesome_flutter: ^10.9.1
  in_app_review: ^2.0.12
  onesignal_flutter: ^5.6.3
  package_info_plus: ^9.0.1
  share_plus: ^12.0.2
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  webview_flutter_wkwebview: ^3.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/title.webp
    - assets/icon-512x512.png

  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/2.png"
