#!/usr/bin/env ruby
# frozen_string_literal: true

require "base64"
require "fileutils"
require "json"
require "optparse"

options = {
  environment: ENV.fetch("APP_ENV", "dev"),
  dart_defines_path: nil,
  output_path: "ios/Flutter/AdMob.generated.xcconfig",
}

OptionParser.new do |parser|
  parser.banner = "Usage: generate_admob_xcconfig.rb [options]"

  parser.on("--environment ENV", "App environment: dev or prod") do |environment|
    options[:environment] = environment
  end

  parser.on("--dart-defines PATH", "Path to dart-define JSON file") do |path|
    options[:dart_defines_path] = path
  end

  parser.on("--output PATH", "Path to generated xcconfig") do |path|
    options[:output_path] = path
  end
end.parse!

def read_dart_defines(path)
  abort "#{path} is required. Copy the matching dart_defines.*.example.json and edit it." unless File.exist?(path)

  parsed = JSON.parse(File.read(path))
  abort "#{path} must contain a JSON object" unless parsed.is_a?(Hash)

  parsed.transform_keys(&:to_s).transform_values(&:to_s)
rescue JSON::ParserError => error
  abort "Invalid JSON in #{path}: #{error.message}"
end

def read_admob_app_id!(defines)
  app_id = defines.fetch("ADMOB_IOS_APP_ID", "").strip
  abort "ADMOB_IOS_APP_ID is required" if app_id.empty?

  unless app_id.include?("~")
    abort "ADMOB_IOS_APP_ID must be an app ID like ca-app-pub-xxxxxxxxxxxxxxxx~xxxxxxxxxx"
  end

  app_id
end

def read_banner_ad_unit_id!(defines)
  banner_ad_unit_id = defines.fetch("ADMOB_IOS_BANNER_AD_UNIT_ID", "").strip
  abort "ADMOB_IOS_BANNER_AD_UNIT_ID is required" if banner_ad_unit_id.empty?
  return banner_ad_unit_id if banner_ad_unit_id.include?("/")

  abort "ADMOB_IOS_BANNER_AD_UNIT_ID must be a banner ad unit ID like ca-app-pub-xxxxxxxxxxxxxxxx/xxxxxxxxxx"
end

def validate_production_ids!(environment, app_id, banner_ad_unit_id)
  return unless environment == "prod"

  values = [app_id, banner_ad_unit_id]
  if values.any? { |value| value.include?("xxxxxxxx") || value.include?("ca-app-pub-3940256099942544") }
    abort "Production AdMob IDs must be real IDs, not placeholders or Google test IDs"
  end
end

def encoded_dart_defines(defines)
  defines.map do |key, value|
    Base64.strict_encode64("#{key}=#{value}")
  end.join(",")
end

environment = options[:environment].strip
abort "environment must be dev or prod" unless %w[dev prod].include?(environment)
options[:dart_defines_path] ||= "dart_defines.#{environment}.json"

defines = read_dart_defines(options[:dart_defines_path])
app_id = read_admob_app_id!(defines)
banner_ad_unit_id = read_banner_ad_unit_id!(defines)
validate_production_ids!(environment, app_id, banner_ad_unit_id)

lines = [
  "// Generated by scripts/generate_admob_xcconfig.rb. Do not edit.",
  "ADMOB_IOS_APP_ID=#{app_id}",
]

dart_defines = encoded_dart_defines(defines)
lines << "DART_DEFINES=#{dart_defines}" unless dart_defines.empty?

FileUtils.mkdir_p(File.dirname(options[:output_path]))
File.write(options[:output_path], "#{lines.join("\n")}\n")
